test: -1
serveAddr: "0.0.0.0:8080"
url: "http://192.168.122.87:8080"
sessionStore: "our-wedding-rsvp"
db: 
  addr: "data/rsvp.db"
  initFile: "init.sql"
admin:
  useOauth2: false
  id: seantywork@gmail.com
  pw: sample
album:
  addr: "public/images"
title: "Taehoon & Suya"
groom: "윤태훈"
bride: "반수야"
comment: "HAPPILY EVER AFTER"
giftPage: "#"
